export const authConstants = {
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_ERROR : "SIGNUP_ERROR",


    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_ERROR: 'SIGNIN_ERROR',


    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_ERROR : "SIGNOUT_ERROR",

    UPDATE_PASSWORD_SUCCESS:'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_ERROR:'UPDATE_PASSWORD_ERROR',

    UPDATE_EMAIL_SUCCESS:'UPDATE_EMAIL_SUCCESS',
    UPDATE_EMAIL_ERROR:'UPDATE_EMAIL_ERROR',

    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR:'RESET_PASSWORD_ERROR',
}

export const timelineConstants = {
    GET_TIMELINE_REQUEST: 'GET_TIMELINE_REQUEST',
    GET_TIMELINE_SUCCESS: 'GET_TIMELINE_SUCCESS',
    GET_TIMELINE_FAILURE: 'GET_TIMELINE_FAILURE',
    
    GET_HISTORY_REQUEST: 'GET_HISTORY_REQUEST',
    GET_HISTORY_SUCCESS: 'GET_HISTORY_SUCCESS',
    GET_HISTORY_FAILURE:'GET_HISTORY_FAILURE',
}

export const listConstants = {
    POST_LIST_REQUEST: 'POST_LIST_REQUEST',
    POST_LIST_SUCCESS: 'POST_LIST_SUCCESS',
    POST_LIST_FAILURE:'POST_LIST_FAILURE'
}

export const userinfoConstants = {
    GET_USERINFO_REQUEST: 'GET_USERINFO_REQUEST',
    GET_USERINFO_SUCCESS: 'GET_USERINFO_SUCCESS',
    GET_USERINFO_FAILURE: 'GET_USERINFO_FAILURE',
    UPDATE_USERINFO:'UPDATE_USERINFO',
    POST_USERINFO_REQUEST:'POST_USERINFO_REQUEST',
    POST_USERINFO_SUCCESS:'POST_USERINFO_SUCCESS',
    POST_USERINFO_FAILURE:'POST_USERINFO_FAILURE',
    USERINFO_NULL:'USERINFO_NULL',
}


export const biddingConstants = {
    POST_BID_REQUEST: 'POST_BID_REQUEST',
    POST_BID_SUCCESS: 'POST_BID_SUCCESS',
    POST_BID_FAILURE:'POST_BID_FAILURE'
}

